In [1]:
import numpy as np

In [2]:
# a 2-dimensional array of size 2 x 4
ar2d = np.array([
    # columns
    # 0    1    2    3
    [7.0, 8.0, 6.0, 5.0],  # 0
    [4.0, 2.0, 1.0, 9.0],  # 1
                           # rows
])
print(ar2d)

[[ 7.  8.  6.  5.]
 [ 4.  2.  1.  9.]]


In [3]:
ar2d.shape

(2, 4)

In [4]:
ar2d[0]

array([ 7.,  8.,  6.,  5.])

In [5]:
ar2d[0, :]

array([ 7.,  8.,  6.,  5.])

In [6]:
print(ar2d[0][0])
ar2d[0][0] == ar2d[0, 0]

7.0


True

In [7]:
# the second row
ar2d[1]

array([ 4.,  2.,  1.,  9.])

In [8]:
# the second column
ar2d[:, 1]

array([ 8.,  2.])

In [9]:
print(ar2d[1][1])
ar2d[1][1] == ar2d[1, 1]

2.0


True

In [10]:
# [row, column]
ar2d[:, 1:3]

array([[ 8.,  6.],
       [ 2.,  1.]])

In [11]:
# a 3-dimensional array of size 2 x 3 x 4
ar3d = np.arange(24).reshape(2, 3, 4)
print(ar3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
ar3d.shape

(2, 3, 4)

In [13]:
mat = np.arange(start=1, stop=7).reshape(3, 2)

In [14]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
mat * np.array([10, 100])

array([[ 10, 200],
       [ 30, 400],
       [ 50, 600]])

In [16]:
height = np.round(np.random.normal(1.76, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
city = np.column_stack((height, weight))

In [17]:
height

array([ 2.01,  1.92,  1.77, ...,  1.76,  1.92,  1.81])

In [18]:
weight

array([ 70.9 ,  65.01,  73.47, ...,  54.42,  60.87,  53.09])

In [19]:
city

array([[  2.01,  70.9 ],
       [  1.92,  65.01],
       [  1.77,  73.47],
       ..., 
       [  1.76,  54.42],
       [  1.92,  60.87],
       [  1.81,  53.09]])

In [20]:
np.corrcoef(city[:, 0], city[:, 1])

array([[ 1.        , -0.01391233],
       [-0.01391233,  1.        ]])

In [21]:
np.std(city[:, 0])

0.19970661151799654

In [22]:
np_positions = np.array(['GK', 'M', 'A', 'D', 'D', 'M'])
np_heights = np.array([191, 184, 185, 183, 179, 179])

In [23]:
# extract all the heights of the goalkeepers
gk_heights = np_heights[np_positions == 'GK']
print(gk_heights)

[191]


In [24]:
# extract all the heights of the all the other players
other_heights = np_heights[np_positions != 'GK']
print(other_heights)

[184 185 183 179 179]


In [25]:
weights = np.array([81.6,  97.0,  95.2])
heights = np.array([1.9,  1.8,  1.7])

In [26]:
bmis = weights / (heights ** 2)
print(bmis)

[ 22.60387812  29.9382716   32.94117647]


In [27]:
light_bmi = bmis[bmis <= 30]
print(light_bmi)

[ 22.60387812  29.9382716 ]


In [28]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [32]:
matrix = np.array([
    [5, 10, 15], 
    [20, 25, 30],
    [35, 40, 45],
])
second_column_25 = matrix[:, 1] == 25
matrix[second_column_25, 1] = 100
print(matrix)

[[  5  10  15]
 [ 20 100  30]
 [ 35  40  45]]


In [35]:
matrix = np.array([
    [5, 10, 15], 
    [20, 25, 30],
    [35, 40, 45]
])

array([ 30,  75, 120])

In [36]:
# perform the operation on each row
matrix.sum(axis=1)

array([ 30,  75, 120])

In [37]:
# perform the operation on each column
matrix.sum(axis=0)

array([60, 75, 90])