In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
%%capture
%run _prepare_data.ipynb

In [3]:
target = train['Survived'].values

In [4]:
features_one = train[['Pclass', 'Sex', 'Age', 'Fare']].values
tree_one = DecisionTreeClassifier()
tree_one.fit(features_one, target)
print(tree_one.feature_importances_)
print(tree_one.score(features_one, target))

[ 0.12780332  0.31274009  0.22713348  0.33232312]
0.977553310887


In [5]:
test_features = test[['Pclass', 'Sex', 'Age', 'Fare']].values

In [6]:
prediction_one = tree_one.predict(test_features)

In [7]:
prediction_one

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0,

In [8]:
PassengerId = np.array(test['PassengerId'])

In [9]:
PassengerId

array([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1040, 1041, 10

In [10]:
solution_one = pd.DataFrame(prediction_one, PassengerId, columns=['Survived'])

In [11]:
solution_one.head()

Survived
892         0
893         0
894         1
895         1
896         1

Limit `max_depth` and `min_samples_split` to make a less complex model.

In [12]:
features_two = train[['Pclass', 'Age', 'Sex', 'Fare']].values
tree_two = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=1)
tree_two.fit(features_two, target)
print(tree_two.feature_importances_)
print(tree_two.score(features_two, target))

[ 0.16349413  0.16408928  0.42846618  0.2439504 ]
0.900112233446


Feature engineering: combine different features into new one.

In [13]:
train_copy = train.copy()
train_copy['FamilySize'] = train_copy['SibSp'] + train_copy['Parch'] + 1

test_copy = test.copy()
test_copy['FamilySize'] = test_copy['SibSp'] + test_copy['Parch'] + 1

predictors = ['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch', 'FamilySize']
features_three = train_copy[predictors].values
tree_three = DecisionTreeClassifier()
tree_three.fit(features_three, target)
print(tree_three.feature_importances_)
print(tree_three.score(features_three, target))

[ 0.10931463  0.31088095  0.23968147  0.24879045  0.01398016  0.01085389
  0.06649846]
0.979797979798


In [14]:
tree = tree_three

test_features = test_copy[predictors].values
prediction = tree.predict(test_features)
print(prediction)

[0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1
 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 0
 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 0 1 1 1 1
 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0
 1 1 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1
 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0
 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1
 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0
 0 1 0 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [15]:
solution = pd.DataFrame(prediction, np.array(test_copy['PassengerId']), columns=['Survived'])

In [16]:
solution.head()

Survived
892         0
893         0
894         1
895         1
896         0

In [17]:
len(solution)

418

In [18]:
solution.to_csv('decision_tree.csv', index_label='PassengerId')