In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
X = [[ 1., -1.,  2.],
     [ 2.,  5.,  3.],
     [ 4.,  1., -1.]]

X = np.array(X)

In [3]:
# mean of the first 3 features
X.mean(axis=0)

array([ 2.33333333,  1.66666667,  1.33333333])

In [4]:
X.std(axis=0)

array([ 1.24721913,  2.49443826,  1.69967317])

In [5]:
preprocessing.scale(X)

array([[-1.06904497, -1.06904497,  0.39223227],
       [-0.26726124,  1.33630621,  0.98058068],
       [ 1.33630621, -0.26726124, -1.37281295]])

In [6]:
from sklearn.preprocessing import StandardScaler

# standardize features to z-scores
standard_scaler = StandardScaler()
scaled_X = standard_scaler.fit_transform(X)
print(scaled_X)

[[-1.06904497 -1.06904497  0.39223227]
 [-0.26726124  1.33630621  0.98058068]
 [ 1.33630621 -0.26726124 -1.37281295]]


In [7]:
from sklearn.preprocessing import MinMaxScaler

# transform features to a given range (0 ~ 1)
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
scaled_X = minmax_scaler.fit_transform(X)
print(scaled_X)

[[ 0.          0.          0.75      ]
 [ 0.33333333  1.          1.        ]
 [ 1.          0.33333333  0.        ]]
